### ISSUE TITLE
TODO: List 

### ISSUE THREAD

**Issue by Thunder07** [Thunder07/Play-#2]
- [ ] Port PsfPlayer to cmake (wip) 
- [ ] Port elf viewer to cmake? Is it buildable without libPlayCore (if so, port might not warranted, unless I go multi platform)
- [ ] Update android db (lost newer db before I updated it *cry*)
